### ISSUE TITLE
`--dry-run` shouldn't require a git token

### ISSUE THREAD

**Issue by tgross35** [release-plz/release-plz#1857]
## Motivations

`--dry-run` seems like it should be helpful for verifying commands locally. However, it isn't always possible to provide a token - this fails with the below:

```text
release --dry-run -o json --backend github
  2024-11-22T20:43:36.155725Z  INFO  using release-plz config file .release-plz.toml

  2024-11-22T20:43:36.176484Z ERROR  git release not configured. Did you specify git-token and backend?

Error: git release not configured. Did you specify git-token and backend?
```

- Would you like to implement this feature? [y/n] n

## Solution

If `--dry-run` is passed, don't look for the token

## Alternatives

Allow something like `GIT_TOKEN=dummy` to indicate that you intend to pass a 

## Additional context

The goal with this command is to figure out whether `release-plz` intends to do a release and build binaries `releases[n].package_name` before actually doing it. After, another job will add the artifacts to the GitHub release. Is this a reasonable way to build and publish release binaries or is there a better workflow?

**Comment by MarcoIeni** [comment]
release-plz uses the git token to determine if a release should be created:

https://github.com/release-plz/release-plz/blob/682264d6afec4ba45d419cfdbab41b7aa97f718d/crates/release_plz_core/src/command/release.rs#L613

Technically if you are using "release_always = true" (which is the default), it's possible to understand if a release will be created or not.

I started implementing this but I realized that this change would complicate the code too much, and it might lead to future errors.

I prefer `release-plz release --dry-run` to use the git token since it's part of the algorithm because I want dry run to reflect what's going on for real and I don't want to overcomplicate the code too much to reflect reality in some cases where that's possible, so I'll close this issue, sorry!

Btw, you can easily get a github token locally by using the gh cli with the command `gh auth token`

**Comment by MarcoIeni** [comment]
> Is this a reasonable way to build and publish release binaries or is there a better workflow?

You approach seems overcomplicated. Plus `-o json` won't give you anything on dry run I think.

For a better approach, see:

- https://release-plz.ieni.dev/docs/extra/releasing-binaries
- https://github.com/release-plz/release-plz/issues/1433

**Comment by tgross35** [comment]
Thanks for the follow up! Makes sense about the git token, I suppose that is required to query repo information.

> You approach seems overcomplicated. Plus `-o json` won't give you anything on dry run I think.

Indeed, I just tested and the output is just `{"releases":[]}` for a dry run.

> For a better approach (imo), see:
> 
>     * https://release-plz.ieni.dev/docs/extra/releasing-binaries
>     * [docs: document how to publish binary in GitHub release from release-plz.yml file #1433](https://github.com/release-plz/release-plz/issues/1433)
> 

> Let me know which approach you end up using :)

I think that both of the links suggest ways to build binaries after the release, correct? I was hoping build the binaries first and then do the release, so the tag/gh release/cargo updates don't get published if there is a bug in the release build process. It's possible to check this manually or via Cargo, but reusing the `release-plz` logic would be more convenient :)

Could `-o json` maybe get a couple more keys for different circumstances? E.g. `no_release` for anything that isn't ready for a release, `potential_releases` for anything that needs a release but wasn't published as part of the last command (that one would help my situation), and `failed_releases` if a release was attempted but failed?

**Comment by MarcoIeni** [comment]
Yes, I'm fine adding more info to the json output.

The first change could be that the dry run would print the same output of the release. So thst you know what packages it wants to publish.

If that's too complicated with dry run we can add another subcommand.

Would you mind opening a new issue if you agree?

**Comment by tgross35** [comment]
Thanks, that would be perfect! I'll open a new issue.
